[theme]
base = "dark"
primaryColor = "#E50914"
backgroundColor = "#07090E"
secondaryBackgroundColor = "#141824"
textColor = "#FFFFFF"
font = "sans serif"

[server]
headless = true
runOnSave = true

[browser]
gatherUsageStats = false
